networks:
  incep_nw:
    name : inet

#Создание томов
volumes:
    ## Здесб хранится  данные wordpress
    wp-volume:
        #Задать имя тому
        name: volume
        driver: local
        driver_opts:
            type: volume
            o: bind
            device: /home/alchrist/inception/data/wp
    # ## Здесб хранится  данные adminer
    # adminer-volume:
    #     #Задать имя тому
    #     name: adminer-volume
    #     driver: local
    #     driver_opts:
    #         type: ext4
    #         o: bind
    #         device: /home/salyce/data/adminer
    ### Здесь храниться mysql
    db-volume:
        name: db-volume
        driver: local
        driver_opts:
            type: volume
            o: bind
            device: /home/alchrist/inception/data/db

services:
  nginx:
    container_name: nginx
    build: ./requirements/nginx
    image: nginx
    networks: 
      - incep_nw
    depends_on:
      - wordpress
    ports:
      - "443:443"
    volumes:
      - wp:/var/www/wordpress
    env_file:
      - .env
    restart: always

  # EXAMPLE for OSRM, please consult the repo for details: https://hub.docker.com/r/osrm/osrm-backend/
  wordpress:
    container_name: wordpress
    networks: 
      - incep_nw
    image: osrm/osrm-backend
    restart: always
    ports:
      - 5000:5000
    volumes:
      - ./osrm:/data
    command: "osrm-routed --max-matching-size 1000 --max-table-size 1000 --max-viar"
    

  mariadb:
    container_name: mariadb
    build: ./requirements/mariadb
    image: mariadb
    ports: 
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: 4m3SxCpaQb*6LB#
      MYSQL_DATABASE: db_wordpress
      MYSQL_USER: user_wp
      MYSQL_PASSWORD: user_wp
    volumes:
      - db:/var/lib/mysql
    networks:
      - project
    restart: always