networks:
  incep_nw:
    name: inet

volumes:
  wp-volume:
    name: volume
    driver: local
    driver_opts:
      type: volume
      o: bind
      device: /home/alchrist/data/wp
  db-volume:
    name: db-volume
    driver: local
    driver_opts:
      type: volume
      o: bind
      device: /home/alchrist/data/db

services:
  nginx:
    container_name: nginx
    build: ./nginx
    networks:
      - incep_nw
    depends_on:
      - wordpress
    ports:
      - "443:443"
      - "80:80"
    volumes:
      - wp-volume:/var/www/wordpress
    env_file:
      - .env
    restart: always

  wordpress:
    container_name: wordpress
    build: ./wordpress
    depends_on:
      - mariadb
    expose:
      - "9000"
    volumes:
      - wp-volume:/var/www/wordpress
    networks:
      - incep_nw
    env_file:
      - .env
    restart: always

  mariadb:
    container_name: mariadb
    build: ./mariadb
    expose:
      - "3306"
    env_file:
      - .env
    volumes:
      - db-volume:/var/lib/mysql
    networks:
      - incep_nw
    restart: always

  redis:
    container_name: redis
    build: ./bonus/redis
    expose:
      - "6379"
    depends_on:
      - wordpress
    networks:
      - incep_nw
    restart: always

  npuzzle:
    container_name: npuzzle
    build: ./bonus/npuzzle
    expose:
      - "8080"
    networks:
      - incep_nw
    restart: always
